Resources:
  awsChatLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: aws-chat-group
      LogGroupClass: STANDARD

  snsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: MessagesTopic
      FifoTopic: false

  sqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MessageQueue
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: 20

  snsAccessXray:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: SnsAccessToXray
      Users:
       - rehan
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: s1
            Effect: Allow
            Resource: "*"
            Action:
              - xray:PutTraceSegments
              - xray:GetSamplingRules
              - xray:GetSamplingTargets
            Condition:
              StringEquals:
                aws:SourceArn: !Ref snsTopic

  snsAccessSqsPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref sqsQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: snsAccessSqsPolicy
            Effect: Allow
            Action: 
              - SQS:SendMessage
              - SQS:SendMessageBatch
            Principal: 
              Service: sns.amazonaws.com
            Resource: !GetAtt sqsQueue.Arn
            Condition:
              ArnEquals: 
                aws:SourceArn: !Ref snsTopic
             
  snsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref snsTopic
      Protocol: sqs
      Endpoint: !GetAtt sqsQueue.Arn
      RawMessageDelivery: true

Outputs:
  QueueARN:
    Description: ARN URL of the SQS Queue
    Value: !GetAtt sqsQueue.Arn
    Export: 
      Name: QueueARN
  QueueURL:
    Description: HTTP URL of the SQS Queue
    Value: !Ref sqsQueue
    Export: 
      Name: QueueURL
  TopicARN:
    Description: ARN for the SNS Topic
    Value: !Ref snsTopic
    Export: 
      Name: TopicARN
  LogGroupName:
    Description: Log Group Name
    Value: !Ref awsChatLogGroup
    Export: 
      Name: LogGroupName